name: Deploy web container
hosts: dmz
become: true

# those can be changed to CLI args if needed 
vars:
  image = simple-web-app:latest
  ports = "80:5000"

tasks:
  - name: pull container image
    docker_container:
      name: webapp
      image: pawluszyn/{{ image }} 
      state: started
      restart_policy: always
      ports: 
        - "{{ ports }}"
